{% set name = "mixsimulator" %}
{% set version = "0.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mixsimulator-{{ version }}.tar.gz
  sha256: 57c92434bfa18ae58aab25a4035da6e7dca0ac80d8be0639601bce110361ffc2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - mixsimulator
    - mixsimulator.centrals

about:
  home: https://github.com/Foloso/MixSimulator
  summary: Python application with nevergrad optimization model for calculating and simulating the least cost of an energy Mix under constraints.
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT
  doc_url: https://pypi.org/project/mixsimulator/
  dev_url: https://github.com/Foloso/MixSimulator

extra:
  recipe-maintainers:
    - JennaLipscomb
    - oblute
